import type { RequestContext } from "../../context/request-context";
import type { DbClient } from "../../db/pool";
import { withTransaction } from "../../db/transaction";
import { conflictError, forbiddenError, isPgError, notFoundError, validationError } from "../../errors";
import { recordAuditEvent } from "../audit/audit.repository";
import { findAppUserByEmail, findAppUserById } from "../users/users.repository";
import {
  findOrganizationById,
  findOrganizationMembershipById,
  findOrganizationMembershipByUserId,
  findPendingOrganizationMembershipByEmail,
  insertOrganization,
  insertOrganizationMembership,
  listMembershipsForUser,
  listOrganizationMemberships,
  listOrganizations,
  updateOrganizationMembershipById
} from "./organizations.repository";
import type {
  CreateOrganizationBody,
  CreateOrganizationMembershipBody,
  ListOrganizationMembershipsQuery,
  ListOrganizationsQuery,
  Organization,
  OrganizationMembership,
  OrganizationMembershipRole,
  PaginatedResponse,
  UpdateOrganizationMembershipBody
} from "./organizations.schemas";

const SLUG_ATTEMPTS = 10;

export function listOrganizationsService(
  query: ListOrganizationsQuery,
  context: RequestContext
): Promise<PaginatedResponse<Organization>> {
  if (context.actor_type === "admin") {
    return listOrganizations(query);
  }

  if (!context.actor_id) {
    throw forbiddenError("Missing authenticated user context.");
  }

  return listOrganizations(query, context.actor_id);
}

export async function getOrganizationService(organizationId: string, context: RequestContext): Promise<Organization> {
  const organization = await findOrganizationById(
    organizationId,
    context.actor_type === "admin" ? undefined : context.actor_id
  );

  if (!organization) {
    throw notFoundError("Organization not found.");
  }

  return organization;
}

export async function createOrganizationService(
  input: CreateOrganizationBody,
  context: RequestContext
): Promise<Organization> {
  if (input.owner_user_id && input.owner_email) {
    throw validationError("Provide only one owner identifier: owner_user_id or owner_email.");
  }

  if (context.actor_type !== "admin" && (input.owner_user_id || input.owner_email)) {
    throw forbiddenError("Only platform administrators can set a different owner during organization creation.");
  }

  const baseSlug = normalizeSlug(input.slug ?? input.name);

  if (!baseSlug) {
    throw validationError("Organization name must produce a valid slug.");
  }

  const autoGeneratedSlug = !input.slug;

  for (let attempt = 0; attempt < SLUG_ATTEMPTS; attempt += 1) {
    const slug = autoGeneratedSlug && attempt > 0 ? `${baseSlug}-${attempt + 1}` : baseSlug;

    try {
      return await withTransaction(async (client) => {
        const organization = await insertOrganization(
          {
            name: input.name.trim(),
            slug,
            created_by_user_id: context.actor_id
          },
          client
        );

        let ownerMembership: OrganizationMembership | null = null;

        if (context.actor_type !== "admin" && context.actor_id) {
          ownerMembership = await insertOrganizationMembership(
            {
              organization_id: organization.id,
              user_id: context.actor_id,
              role: "owner",
              status: "active",
              created_by_user_id: context.actor_id
            },
            client
          );
        } else if (input.owner_user_id || input.owner_email) {
          ownerMembership = await createOrUpsertMembership(
            organization.id,
            {
              user_id: input.owner_user_id,
              email: input.owner_email,
              role: "owner"
            },
            context,
            client
          );
        }

        await recordAuditEvent(
          {
            ...context,
            organization_id: organization.id,
            action: "organization.created",
            resource_type: "organization",
            resource_id: organization.id,
            metadata: {
              slug: organization.slug,
              owner_membership_id: ownerMembership?.id ?? null
            }
          },
          client
        );

        return {
          ...organization,
          current_membership:
            context.actor_type !== "admin" && ownerMembership
              ? { id: ownerMembership.id, role: ownerMembership.role, status: ownerMembership.status }
              : null
        };
      });
    } catch (error) {
      if (isPgError(error, "23505")) {
        if (autoGeneratedSlug) {
          continue;
        }

        throw conflictError("An organization with this slug already exists.");
      }

      throw error;
    }
  }

  throw conflictError("Could not allocate a unique organization slug.");
}

export async function listOrganizationMembershipsService(
  organizationId: string,
  query: ListOrganizationMembershipsQuery
): Promise<PaginatedResponse<OrganizationMembership>> {
  const memberships = await listOrganizationMemberships(organizationId, query);

  if (memberships.pagination.total === 0) {
    const organization = await findOrganizationById(organizationId);

    if (!organization) {
      throw notFoundError("Organization not found.");
    }
  }

  return memberships;
}

export async function createOrganizationMembershipService(
  organizationId: string,
  input: CreateOrganizationMembershipBody,
  context: RequestContext
): Promise<OrganizationMembership> {
  if (input.user_id && input.email) {
    throw validationError("Provide only one target: user_id or email.");
  }

  if (context.actor_type !== "admin" && input.role === "owner") {
    throw forbiddenError("Only platform administrators can assign the owner role.");
  }

  const organization = await findOrganizationById(organizationId);

  if (!organization) {
    throw notFoundError("Organization not found.");
  }

  return withTransaction(async (client) => {
    const membership = await createOrUpsertMembership(organizationId, input, context, client);

    await recordAuditEvent(
      {
        ...context,
        organization_id: organizationId,
        action: "organization_membership.created_or_updated",
        resource_type: "organization_membership",
        resource_id: membership.id,
        metadata: {
          role: membership.role,
          status: membership.status,
          user_id: membership.user_id,
          invite_email: membership.invite_email
        }
      },
      client
    );

    const hydratedMembership = await findOrganizationMembershipById(organizationId, membership.id, client);

    if (!hydratedMembership) {
      throw notFoundError("Organization membership not found after creation.");
    }

    return hydratedMembership;
  });
}

export async function updateOrganizationMembershipService(
  organizationId: string,
  membershipId: string,
  input: UpdateOrganizationMembershipBody,
  context: RequestContext
): Promise<OrganizationMembership> {
  if (Object.keys(input).length === 0) {
    throw validationError("At least one organization membership field must be provided.");
  }

  const existingMembership = await findOrganizationMembershipById(organizationId, membershipId);

  if (!existingMembership) {
    throw notFoundError("Organization membership not found.");
  }

  if (context.actor_type !== "admin" && (existingMembership.role === "owner" || input.role === "owner")) {
    throw forbiddenError("Only platform administrators can modify owner memberships.");
  }

  const updatedMembership = await withTransaction(async (client) => {
    const membership = await updateOrganizationMembershipById(
      organizationId,
      membershipId,
      {
        role: input.role,
        status: input.status
      },
      client
    );

    if (!membership) {
      throw notFoundError("Organization membership not found.");
    }

    await recordAuditEvent(
      {
        ...context,
        organization_id: organizationId,
        action: "organization_membership.updated",
        resource_type: "organization_membership",
        resource_id: membership.id,
        metadata: {
          changed_fields: Object.keys(input),
          role: membership.role,
          status: membership.status
        }
      },
      client
    );

    return membership;
  });

  const hydratedMembership = await findOrganizationMembershipById(organizationId, updatedMembership.id);

  if (!hydratedMembership) {
    throw notFoundError("Organization membership not found after update.");
  }

  return hydratedMembership;
}

export async function listMyMembershipsService(userId: string): Promise<OrganizationMembership[]> {
  return listMembershipsForUser(userId);
}

function normalizeSlug(value: string): string {
  return value
    .normalize("NFKD")
    .replace(/[^\x00-\x7F]/g, "")
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 120);
}

async function createOrUpsertMembership(
  organizationId: string,
  input: {
    user_id?: string;
    email?: string;
    role: OrganizationMembershipRole;
  },
  context: RequestContext,
  client: DbClient
): Promise<OrganizationMembership> {
  const normalizedEmail = input.email?.trim().toLowerCase();
  const resolvedUser = input.user_id
    ? await findAppUserById(input.user_id, client)
    : normalizedEmail
      ? await findAppUserByEmail(normalizedEmail, client)
      : null;

  if (input.user_id && !resolvedUser) {
    throw notFoundError("App user not found. The user must log in once or be assigned by email.");
  }

  const targetUserId = resolvedUser?.id ?? input.user_id;
  const targetInviteEmail = normalizedEmail ?? resolvedUser?.email ?? undefined;
  const targetStatus = resolvedUser || input.user_id ? "active" : "invited";

  if (!targetUserId && !targetInviteEmail) {
    throw validationError("A membership target user_id or email is required.");
  }

  if (targetUserId) {
    const existingByUserId = await findOrganizationMembershipByUserId(organizationId, targetUserId, client);

    if (existingByUserId) {
      const updatedMembership = await updateOrganizationMembershipById(
        organizationId,
        existingByUserId.id,
        {
          user_id: targetUserId,
          invite_email: resolvedUser?.email ?? existingByUserId.invite_email ?? undefined,
          role: input.role,
          status: "active"
        },
        client
      );

      if (!updatedMembership) {
        throw notFoundError("Organization membership not found.");
      }

      return updatedMembership;
    }
  }

  if (targetInviteEmail) {
    const existingByEmail = await findPendingOrganizationMembershipByEmail(organizationId, targetInviteEmail, client);

    if (existingByEmail) {
      const updatedMembership = await updateOrganizationMembershipById(
        organizationId,
        existingByEmail.id,
        {
          user_id: targetUserId,
          invite_email: targetInviteEmail,
          role: input.role,
          status: targetStatus
        },
        client
      );

      if (!updatedMembership) {
        throw notFoundError("Organization membership not found.");
      }

      return updatedMembership;
    }
  }

  return insertOrganizationMembership(
    {
      organization_id: organizationId,
      user_id: targetUserId,
      invite_email: targetUserId ? resolvedUser?.email ?? targetInviteEmail : targetInviteEmail,
      role: input.role,
      status: targetStatus,
      created_by_user_id: context.actor_id
    },
    client
  );
}
